### ISSUE TITLE
Dokumentacja projektu

### ISSUE THREAD

**Issue by schkatz** [schkatz/Projekt#3]
Zadanie dla: *nas*
Do zrobienia: *Wstępna dokumentacja projektu*
Kryteria zaliczenia:
- Opis funkcjonalny
- Opis niefunkcjonalny
- Diagram ERD bazy danych
- Wstępna architektura

**Comment by GrzegorzKatze** [comment]
"No one assigned"

**Comment by schkatz** [comment]
Dodać diagram ERD bazy danych.

@edit
Diagram dodany
